* from a import b : a 모듈(혹은 패키지)에서 b 함수를 가져오겠다. b를 사용하기 위해선 b() 꼴 로 사용 가능
* import a : a 모듈을 불러오겠다. a 모듈 안에있는 b 함수를 사용하기 위해선 a.b() 꼴로 사용해야함

In [2]:
from random import randrange
import math

var1 = randrange(1,11)

var2 = math.log(5184, 72)

print(var1, var2)

6 2.0


* Python에서는 쉽게 웹페이지의 정보를 가져올 수 있는 urllib패키지를 제공합니다. 이 중에서 urllib.request.urlopen 함수는 해당 url의 html 파일을 가져옵니다.

* 위 함수를 이용해서 https://en.wikipedia.org/wiki/Lorem_ipsum 홈페이지의 정보를 가져와봅시다.

In [3]:
from urllib.request import urlopen #from 패키지.모듈 import 함수

var = urlopen('https://en.wikipedia.org/wiki/Lorem_ipsum').read().decode("utf-8")

print(var)

<!DOCTYPE html>
<html class="client-nojs" lang="en" dir="ltr">
<head>
<meta charset="UTF-8"/>
<title>Lorem ipsum - Wikipedia</title>
<script>document.documentElement.className="client-js";RLCONF={"wgBreakFrames":!1,"wgSeparatorTransformTable":["",""],"wgDigitTransformTable":["",""],"wgDefaultDateFormat":"dmy","wgMonthNames":["","January","February","March","April","May","June","July","August","September","October","November","December"],"wgRequestId":"f6a16b2b-3baa-4085-9f76-10a49dd91fd7","wgCSPNonce":!1,"wgCanonicalNamespace":"","wgCanonicalSpecialPageName":!1,"wgNamespaceNumber":0,"wgPageName":"Lorem_ipsum","wgTitle":"Lorem ipsum","wgCurRevisionId":1035139868,"wgRevisionId":1035139868,"wgArticleId":190246,"wgIsArticle":!0,"wgIsRedirect":!1,"wgAction":"view","wgUserName":null,"wgUserGroups":["*"],"wgCategories":["CS1 maint: unfit URL","CS1 Latin-language sources (la)","Articles with short description","Short description is different from Wikidata","Articles containing Latin-language t

## Numpy(Numerical Python)

- Python에서 대규모 다차원 배열을 다룰 수 있게 도와주는 라이브러리

* 왜 Numpy를 사용하는가?
    * 반복문 없이 배열 처리가능
    * 파이썬 리스트에 비해, 빠른 연산을 지원하고 메모리를 효율적으로 사용

In [11]:
list_arr = list(range(10))
print(list_arr)
print(type(list_arr))

Wall time: 0 ns
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
<class 'list'>


In [12]:
import numpy as np # numpy모듈불러와서‘np’별칭부여

np_arr = np.array(range(10))
print(np_arr)
print(type(np_arr))

Wall time: 0 ns
[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


In [13]:
# 파이썬 리스트와 달리 같은 데이터 타입만 저장 가능
arr = np.array([0, 1, 2, 3, 4, 5], dtype = float)
print(arr)
print(arr.dtype)
print(arr.astype(int))

[0. 1. 2. 3. 4. 5.]
float64
[0 1 2 3 4 5]


|dtype|설명|다양한 표현|
|:------:|:---:|:---:|
|int|정수형|i, int, int32, int64, i8|
|float|실수형|f, float_, float32, float64, f8|
|str|문자형|str, U, U32|
|bool|부울|?, bool|

### ndarray 의 차원 관련 속성 : ndim & shape


In [14]:
# 1차원 배열
list = [0, 1, 2, 3]
arr = np.array(list)
print(arr.ndim)
print(arr.shape)

1
(4,)


In [15]:
# 2차원 배열
list = [[0, 1, 2], [3, 4, 5]]
arr = np.array(list)
print(arr.ndim)
print(arr.shape)

2
(2, 3)


In [18]:
# ndarray의 크기 속성과 shape 조절

arr = np.array([0, 1, 2, 3, 4,5])
print('arr.shape: {}'.format(arr.shape))
print('배열 요소의 수: {}'.format(arr.size))
print("배열의 길이:{}".format(len(arr)))

arr.shape: (6,)
배열 요소의 수: 6
배열의 길이:6


In [20]:
arr.shape= 3, 2
print("arr.shape: {}".format(arr.shape)) 
print("배열 요소의 수:{}".format(arr.size)) 
print("배열의 길이:{}".format(len(arr)))

arr.shape: (3, 2)
배열 요소의 수:6
배열의 길이:3


### Indexing & Slicing

In [25]:
# indexing : 인덱스로 값을 찾아냄

x = np.arange(7)
print(x)
print(x[3])
# print(x[7]) #IndexError: index 7 is out of bounds for axis 0 with size 7

x[0] = 10 # 0번째 값 바꾸기
print(x)

[0 1 2 3 4 5 6]
3
[10  1  2  3  4  5  6]


In [27]:
# 2차원 배열
x = np.arange(1, 13, 1) # 1부터 12까지 1씩 증가
x.shape = 3, 4
print(x)

print(x[2, 3])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
12


In [33]:
# slicing : 인덱스의 값으로 배열의 일부분을 가져옴

x = np.arange(7)
print(x)

print(x[1:4]) # 1번째 부터 4번째 전까지
print(x[1:]) # 1번째 이후 전체
print(x[:4]) # 4번째 전까지
print(x[::2]) # 2씩 증가해서 출력

[0 1 2 3 4 5 6]
[1 2 3]
[1 2 3 4 5 6]
[0 1 2 3]
[0 2 4 6]


In [36]:
# 2차원 배열
x = np.arange(1, 13, 1)
x.shape = 3, 4
print(x)

print(x[1:2,2:3])
print(x[1:,:2])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[7]]
[[ 5  6]
 [ 9 10]]


In [38]:
# Boolean indexing : 배열의 각 요소의 선택 여부를 Boolean mask를 이용하여 지정하는 방식

x = np.arange(7)
print(x)

# Boolean mask? True,False로구성된maskarray
print(x < 3)
print(x > 7)

# Boolean mask의True요소에해당하는index만을조회
print(x[x < 3])
print(x[x % 2 == 0])

[0 1 2 3 4 5 6]
[ True  True  True False False False False]
[False False False False False False False]
[0 1 2]
[0 2 4 6]


In [39]:
# Fancy indexing : 배열의 각 요소 선택을 Index 배열을 전달하여 지정하는 방식

x = np.arange(7)
print(x)

print(x[[1, 3, 5]])

[0 1 2 3 4 5 6]
[1 3 5]


In [41]:
# 2차원 배열
x = np.arange(1, 13, 1 ).reshape(3, 4)
print(x)

print(x[[0, 2]])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3  4]
 [ 9 10 11 12]]


In [42]:
# 원하는 요소를 지정하기 위해 Indexing과 Slicing을 적절히 조합하여 사용가능
x = np.arange(1, 13, 1).reshape(3, 4)
print(x)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [43]:
print(x[1:2, 2])

[7]


In [44]:
print(x[[0, 2], 2])

[ 3 11]


In [45]:
print(x[[0, 2], :2])

[[ 1  2]
 [ 9 10]]


### 실습 1

In [47]:
import numpy as np

# 0부터 4까지 연속적인 숫자가 들어있는 배열을 만들어 봅시다!
array = np.array(range(5))
print(array)

[0 1 2 3 4]


In [48]:
array2 = np.arange(5)
print(array2)

[0 1 2 3 4]


### 실습 2

In [49]:
import numpy as np

print("1차원 array")
array = np.array(range(10))
print(array)

# 1. array의 자료형을 출력해보세요.
print(type(array))

# 2. array의 차원을 출력해보세요.
print(array.ndim)

# 3. array의 모양을 출력해보세요.
print(array.shape)

# 4. array의 크기를 출력해보세요.
print(array.size)

# 5. array의 dtype(data type)을 출력해보세요.
print(array.dtype)

# 6. array의 인덱스 5의 요소를 출력해보세요.
print(array[5])

# 7. array의 인덱스 3의 요소부터 인덱스 5 요소까지 출력해보세요.
print(array[3:6])


1차원 array
[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
1
(10,)
10
int32
5
[3 4 5]


In [50]:
import numpy as np

print("2차원 array")
#1부터 15까지 들어있는 (3,5)짜리 배열을 만듭니다.
matrix = np.array(range(1,16))
matrix.shape = 3,5
print(matrix)


# 1. matrix의 자료형을 출력해보세요.
print(type(matrix))

# 2. matrix의 차원을 출력해보세요.
print(matrix.ndim)

# 3. matrix의 모양을 출력해보세요.
print(matrix.shape)

# 4. matrix의 크기를 출력해보세요.
print(matrix.size)

# 5. matrix의 dtype(data type)을 출력해보세요.
print(matrix.dtype)

# 6. matrix의 dtype을 str로 변경하여 출력해보세요.
print(matrix.astype(str))

# 7. matrix의 (2,3) 인덱스의 요소를 출력해보세요.
print(matrix[2,3])

# 8. matrix의 행은 인덱스 0부터 인덱스 1까지, 열은 인덱스 1부터 인덱스 3까지 출력해보세요.
print(matrix[0:2,1:4])

2차원 array
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
<class 'numpy.ndarray'>
2
(3, 5)
15
int32
[['1' '2' '3' '4' '5']
 ['6' '7' '8' '9' '10']
 ['11' '12' '13' '14' '15']]
14
[[2 3 4]
 [7 8 9]]
